name: Build and push packages

on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: 'flowforge/github-actions-workflows/.github/workflows/build_node_package_with_pgsql.yml@main'
    with:
      run_tests: true
  
  publish:
    needs: build
    if: |
      ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) ||
      github.event_name == 'schedule'
    uses: 'flowforge/github-actions-workflows/.github/workflows/publish_node_package.yml@main'
    with:
      package_name: flowforge-file-server
      publish_package: true

  dispatch_container_build:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}
      - name: Trigger flie-server container image build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: fileserver-container.yml
          repo: flowforge/helm
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
          inputs: '{"fileserver_ref": "${{ github.ref }}", "fileserver_release_name": "${{ needs.publish.outputs.release_name }}"}'
