on: 
  push: 
    tags:
      - "v*.*.*"

jobs:
  build_application_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: flowforge/flowforge-file-server
          path: flowforge-file-server

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=semver,event=tag,pattern={{version}}
          images: |
            flowforge/file-server

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push FlowForge Application container
        uses: docker/build-push-action@v2
        with:
          context: flowforge-file-server
          file: flowforge-file-server/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - name: Push README
        uses: peter-evans/dockerhub-description@v3
        with:
          repository: flowforge/file-server
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          readme-filepath: ./flowforge-file-server/README.md